"""
source.py

SourceRepository for the metadata-driven ingestion framework.

Encapsulates SQL queries specific to the `source` metadata table.
All generic CRUD behavior (create, update, delete, get_by_id, exists)
is inherited from BaseRepository and reused here rather than
reimplemented.
"""

import logging
from pathlib import Path
from typing import Any, Optional, Union

import psycopg2
from psycopg2.extensions import connection as PGConnection
from psycopg2.extras import RealDictCursor
from psycopg2 import sql

from data_engineering_layer.metadata_manager.OOP.baserepo import (
    BaseRepository,
    RepositoryError,
)
from data_engineering_layer.metadata_manager.OOP.datasets import DatasetRepository
from data_engineering_layer.metadata_manager.OOP.yml_parser import YamlParser

logger = logging.getLogger(__name__)


class SourceRepository(BaseRepository):
    """
    Repository for the `source` metadata table.

    Responsible for encapsulating SQL queries and persistence
    operations specific to source records.

    YAML parsing is delegated to YamlParser. Resolving a dataset's
    database id is delegated to DatasetRepository. This repository
    does not perform pipeline orchestration or metadata validation.
    """

    def __init__(self, connection: PGConnection) -> None:
        """
        Initialize the SourceRepository.

        Args:
            connection: An open psycopg2 connection.
        """
        super().__init__(
            connection=connection,
            schema="metadata_manager",
            table_name="source",
            primary_key="id",
        )
        self._dataset_repo = DatasetRepository(connection)

    def register(self, source: Union[dict[str, Any], Any]) -> dict[str, Any]:
        """
        Register a single source record, skipping it if an equivalent
        record already exists.

        Duplicates are matched on (dataset_id, type, path, file_type)
        via exists(), mirroring how DatasetRepository.register() matches
        on `name`. The `id` column is never set here; it is generated by
        the table's SERIAL default on insert.

        Args:
            source: Column-value pairs for the source row (dataset_id,
                type, path, file_type), or an object exposing to_dict().

        Returns:
            The existing matching record if one is found, otherwise the
            newly created record.

        Raises:
            RepositoryError: If dataset_id is missing or the insert fails.
        """
        data = source.to_dict() if hasattr(source, "to_dict") else source

        if not data.get("dataset_id"):
            raise RepositoryError("Source dataset_id is required.")

        if self.is_registered(data):
            logger.info(
                "Source already registered for dataset_id=%s, path=%s",
                data.get("dataset_id"),
                data.get("path"),
            )
            return self._find_one({k: v for k, v in data.items() if v is not None})

        return self.create(data)

    def is_registered(self, source: dict[str, Any]) -> bool:
        """
        Determine whether an equivalent source has already been registered.

        Matches on whichever of dataset_id/type/path/file_type are
        present in `source`, mirroring how
        DatasetRepository.is_registered() wraps exists() for the
        dataset table's uniqueness rule (there, `name`; here, the
        combination of populated source fields).

        Args:
            source: Column-value pairs to match against.

        Returns:
            True if a matching row exists, False otherwise.
        """
        filters = {k: v for k, v in source.items() if v is not None}
        return self.exists(filters) if filters else False

    def _find_one(self, filters: dict[str, Any]) -> Optional[dict[str, Any]]:
        """
        Fetch a single row matching arbitrary column-value filters.

        Thin helper built on the same query-composition approach as
        BaseRepository.exists(), reused here to avoid a bespoke SELECT.

        Args:
            filters: Column-value pairs to match, combined with AND.

        Returns:
            The first matching row as a dictionary, or None if not found.

        Raises:
            RepositoryError: If filters is empty or the query fails.
        """
        if not filters:
            raise RepositoryError("Cannot look up a record with empty filters.")

        columns = list(filters.keys())
        values = list(filters.values())

        conditions = sql.SQL(" AND ").join(
            sql.SQL("{col} = {placeholder}").format(
                col=sql.Identifier(col), placeholder=sql.Placeholder()
            )
            for col in columns
        )

        query = sql.SQL("SELECT * FROM {table} WHERE {conditions} LIMIT 1").format(
            table=self._table_identifier(),
            conditions=conditions,
        )

        try:
            with self._connection.cursor(cursor_factory=RealDictCursor) as cursor:
                cursor.execute(query, values)
                row = cursor.fetchone()
                return dict(row) if row else None
        except psycopg2.Error as exc:
            raise RepositoryError(
                f"Failed to look up record in '{self._table_name}': {exc}"
            ) from exc

    def get_by_dataset_id(self, dataset_id: Any) -> Optional[dict[str, Any]]:
        """
        Retrieve the source row registered for a dataset.

        A dataset is expected to back exactly one source under the
        current schema (this mirrors the single-row lookup the
        integration test does by hand today). If that assumption ever
        changes, add a get_all_by_dataset_id() rather than overloading
        this method's return type.

        Args:
            dataset_id: Primary key of the parent dataset.

        Returns:
            The source row as a dictionary, or None if not found.

        Raises:
            RepositoryError: If the query fails.
        """
        return self._find_one({"dataset_id": dataset_id})

    def register_from_directory(
        self,
        metadata_dir: Union[str, Path] = "metadata",
    ) -> list[dict[str, Any]]:
        """
        Scan a directory tree for source metadata YAML files and register
        each source that isn't already present in the `source` table.

        YAML file discovery and parsing are delegated to YamlParser.
        This method is responsible for interpreting the `dataset` and
        `source` blocks: the dataset `name` is resolved to a database
        `dataset_id` via DatasetRepository.get_id(), and the `source`
        block supplies `type`, `path`, and `file_type`.

        Duplicates are matched on (dataset_id, type, path, file_type)
        via exists(), inside register(). A source that is already
        registered is skipped rather than updated.

        A file that is missing the `dataset`/`source` blocks, missing a
        dataset `name`, references an unregistered dataset, or fails to
        register is logged and skipped.

        Args:
            metadata_dir: Root directory to scan for *.yml files recursively.

        Returns:
            The source records that were newly inserted.

        Raises:
            RepositoryError: If metadata_dir does not exist or isn't a directory.
        """
        parser = YamlParser()

        try:
            parsed_files = parser.parse_directory(metadata_dir)
        except (ValueError, OSError) as exc:
            raise RepositoryError(str(exc)) from exc

        inserted: list[dict[str, Any]] = []

        for yml_path, parsed in parsed_files:
            try:
                dataset_block = parsed.get("dataset")
                source_block = parsed.get("source")

                if not isinstance(dataset_block, dict):
                    raise ValueError("missing top-level 'dataset' block")

                if not isinstance(source_block, dict):
                    raise ValueError("missing top-level 'source' block")

                dataset_name = dataset_block.get("name")

                if not dataset_name:
                    raise ValueError(
                        "'dataset' block is missing required 'name' field"
                    )

                dataset_id = self._dataset_repo.get_id(dataset_name)

                if dataset_id is None:
                    raise ValueError(
                        f"dataset '{dataset_name}' is not registered; "
                        "register it before its sources"
                    )

                data = {
                    "dataset_id": dataset_id,
                    "type": source_block.get("type"),
                    "path": source_block.get("path"),
                    "file_type": source_block.get("file_type"),
                }

                if self.is_registered(data):
                    logger.info(
                        "Skipping source for dataset '%s' (%s): already registered",
                        dataset_name,
                        yml_path,
                    )
                    continue

                record = self.register(data)
                inserted.append(record)

                logger.info(
                    "Registered source for dataset '%s' from %s",
                    dataset_name,
                    yml_path,
                )

            except (ValueError, RepositoryError) as exc:
                logger.error(
                    "Failed to process metadata file '%s': %s",
                    yml_path,
                    exc,
                )
                continue

        return inserted

