"""
target.py

TargetRepository for the metadata-driven ingestion framework.

Encapsulates SQL queries specific to the `target` metadata table.
All generic CRUD behavior (create, update, delete, get_by_id, exists)
is inherited from BaseRepository and reused here rather than
reimplemented.
"""

import logging
from pathlib import Path
from typing import Any, Optional, Union

import psycopg2
from psycopg2.extensions import connection as PGConnection
from psycopg2.extras import RealDictCursor
from psycopg2 import sql

from data_engineering_layer.metadata_manager.OOP.baserepo import (
    BaseRepository,
    RepositoryError,
)
from data_engineering_layer.metadata_manager.OOP.datasets import DatasetRepository
from data_engineering_layer.metadata_manager.OOP.yml_parser import YamlParser


logger = logging.getLogger(__name__)


class TargetRepository(BaseRepository):
    """
    Repository for the `target` metadata table.

    Responsible for encapsulating SQL queries and persistence
    operations specific to target records.

    YAML parsing is delegated to YamlParser.
    """

    def __init__(self, connection: PGConnection) -> None:
        """
        Initialize the TargetRepository.

        Args:
            connection: An open psycopg2 connection.
        """
        super().__init__(
            connection=connection,
            schema="metadata_manager",
            table_name="target",
            primary_key="id",
        )
        self._dataset_repo = DatasetRepository(connection)


    def register(self, target: Union[dict[str, Any], Any]) -> dict[str, Any]:
        """
        Register a single target record, skipping it if an equivalent
        record already exists.

        Duplicates are matched on (database, schema, table) via
        is_registered(), mirroring how DatasetRepository.register()
        matches on `name`. The `id` column is never set here; it is
        generated by the table's SERIAL default on insert.

        Args:
            target: Column-value pairs for the target row (database,
                schema, table), or an object exposing to_dict().

        Returns:
            The existing matching record if one is found, otherwise the
            newly created record.

        Raises:
            RepositoryError: If the insert fails.
        """
        data = target.to_dict() if hasattr(target, "to_dict") else target

        if self.is_registered(data):
            logger.info(
                "Target already registered for database=%s, schema=%s, table=%s",
                data.get("database"),
                data.get("schema"),
                data.get("table"),
            )
            return self._find_one({k: v for k, v in data.items() if v is not None})

        return self.create(data)

    def is_registered(self, target: dict[str, Any]) -> bool:
        """
        Determine whether an equivalent target has already been registered.

        Matches on whichever of database/schema/table are present in
        `target`, mirroring how DatasetRepository.is_registered() wraps
        exists() for the dataset table's uniqueness rule (there,
        `name`; here, the combination of populated target fields).

        Args:
            target: Column-value pairs to match against.

        Returns:
            True if a matching row exists, False otherwise.
        """
        filters = {k: v for k, v in target.items() if v is not None}
        return self.exists(filters) if filters else False

    def _find_one(self, filters: dict[str, Any]) -> Optional[dict[str, Any]]:
        """
        Fetch a single row matching arbitrary column-value filters.

        Thin helper built on the same query-composition approach as
        BaseRepository.exists(), reused here to avoid a bespoke SELECT.

        Args:
            filters: Column-value pairs to match, combined with AND.

        Returns:
            The first matching row as a dictionary, or None if not found.

        Raises:
            RepositoryError: If filters is empty or the query fails.
        """
        if not filters:
            raise RepositoryError("Cannot look up a record with empty filters.")

        columns = list(filters.keys())
        values = list(filters.values())

        conditions = sql.SQL(" AND ").join(
            sql.SQL("{col} = {placeholder}").format(
                col=sql.Identifier(col), placeholder=sql.Placeholder()
            )
            for col in columns
        )

        query = sql.SQL("SELECT * FROM {table} WHERE {conditions} LIMIT 1").format(
            table=self._table_identifier(),
            conditions=conditions,
        )

        try:
            with self._connection.cursor(cursor_factory=RealDictCursor) as cursor:
                cursor.execute(query, values)
                row = cursor.fetchone()
                return dict(row) if row else None
        except psycopg2.Error as exc:
            raise RepositoryError(
                f"Failed to look up record in '{self._table_name}': {exc}"
            ) from exc

    def get_by_dataset_id(self, dataset_id: Any) -> Optional[dict[str, Any]]:
        """
        Retrieve the target row registered for a dataset.

        A dataset is expected to back exactly one target under the
        current schema; see SourceRepository.get_by_dataset_id() for
        the same assumption on the source side.

        Args:
            dataset_id: Primary key of the parent dataset.

        Returns:
            The target row as a dictionary, or None if not found.

        Raises:
            RepositoryError: If the query fails.
        """
        return self._find_one({"dataset_id": dataset_id})

    def register_from_directory(
        self,
        metadata_dir: Union[str, Path] = "metadata",
    ) -> list[dict[str, Any]]:
        """
        Scan a directory tree for target metadata YAML files and register
        each target that isn't already present in the `target` table.

        YAML file discovery and parsing are delegated to YamlParser.
        This method is responsible for interpreting the `dataset` and
        `target` blocks: the dataset `name` is resolved to a database
        `dataset_id` via DatasetRepository.get_id(), and the `target`
        block supplies `database`, `schema`, and `table`.

        Duplicates are matched on (database, schema, table) via
        is_registered(). A target that is already registered is
        skipped rather than updated.

        A file that is missing the `dataset`/`target` blocks, missing a
        dataset `name`, references an unregistered dataset, or fails to
        register is logged and skipped.

        Args:
            metadata_dir: Root directory to scan for *.yml files recursively.

        Returns:
            The target records that were newly inserted.

        Raises:
            RepositoryError: If metadata_dir does not exist or isn't a directory.
        """
        parser = YamlParser()

        try:
            parsed_files = parser.parse_directory(metadata_dir)
        except (ValueError, OSError) as exc:
            raise RepositoryError(str(exc)) from exc

        inserted: list[dict[str, Any]] = []

        for yml_path, parsed in parsed_files:
            try:
                target_block = parsed.get("target")
                dataset_block = parsed.get("dataset")

                if not isinstance(target_block, dict):
                    raise ValueError("missing top-level 'target' block")

                if not isinstance(dataset_block, dict):
                    raise ValueError("missing top-level 'dataset' block")

                dataset_name = dataset_block.get("name")

                if not dataset_name:
                    raise ValueError(
                        "'dataset' block is missing required 'name' field"
                    )

                dataset_id = self._dataset_repo.get_id(dataset_name)

                if dataset_id is None:
                    raise ValueError(
                        f"dataset '{dataset_name}' is not registered; "
                        "register it before its target"
                    )

                data = {
                    "dataset_id": dataset_id,
                    "database": target_block.get("database"),
                    "schema": target_block.get("schema"),
                    "table": target_block.get("table"),
                }

                if self.is_registered(data):
                    logger.info(
                        "Skipping target (%s): already registered",
                        yml_path,
                    )
                    continue

                record = self.register(data)
                inserted.append(record)

                logger.info(
                    "Registered target %s.%s.%s for dataset_id=%s from %s",
                    data.get("database"),
                    data.get("schema"),
                    data.get("table"),
                    data.get("dataset_id"),
                    yml_path,
                )

            except (ValueError, RepositoryError) as exc:
                logger.error(
                    "Failed to process metadata file '%s': %s",
                    yml_path,
                    exc,
                )
                continue

        return inserted

